name: Example doc
url: "https://bferrema.github.io"
#theme: jekyll-theme-minimal
markdown: kramdown
title: Menu
description: 
#links:
#  section_1:
#    - title: home
#      url: /
#      key_trigger: 1
#    - title: my posts
#      url: /posts
#      key_trigger: 2
